// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0--rc3
// source: service_happy_wallet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HappyWallet_CreateUser_FullMethodName = "/pb.HappyWallet/CreateUser"
	HappyWallet_LoginUser_FullMethodName  = "/pb.HappyWallet/LoginUser"
)

// HappyWalletClient is the client API for HappyWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HappyWalletClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type happyWalletClient struct {
	cc grpc.ClientConnInterface
}

func NewHappyWalletClient(cc grpc.ClientConnInterface) HappyWalletClient {
	return &happyWalletClient{cc}
}

func (c *happyWalletClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, HappyWallet_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *happyWalletClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, HappyWallet_LoginUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HappyWalletServer is the server API for HappyWallet service.
// All implementations must embed UnimplementedHappyWalletServer
// for forward compatibility
type HappyWalletServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedHappyWalletServer()
}

// UnimplementedHappyWalletServer must be embedded to have forward compatible implementations.
type UnimplementedHappyWalletServer struct {
}

func (UnimplementedHappyWalletServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedHappyWalletServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedHappyWalletServer) mustEmbedUnimplementedHappyWalletServer() {}

// UnsafeHappyWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HappyWalletServer will
// result in compilation errors.
type UnsafeHappyWalletServer interface {
	mustEmbedUnimplementedHappyWalletServer()
}

func RegisterHappyWalletServer(s grpc.ServiceRegistrar, srv HappyWalletServer) {
	s.RegisterService(&HappyWallet_ServiceDesc, srv)
}

func _HappyWallet_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HappyWalletServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HappyWallet_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HappyWalletServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HappyWallet_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HappyWalletServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HappyWallet_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HappyWalletServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HappyWallet_ServiceDesc is the grpc.ServiceDesc for HappyWallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HappyWallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HappyWallet",
	HandlerType: (*HappyWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _HappyWallet_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _HappyWallet_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_happy_wallet.proto",
}
