services:
  # mongodb:
  #   image: 'mongo'
  #   volumes: 
  #     - data:/data/db
  #   # environment: 
  #   #   MONGO_INITDB_ROOT_USERNAME: max
  #   #   MONGO_INITDB_ROOT_PASSWORD: secret
  #     # - MONGO_INITDB_ROOT_USERNAME=max
  #   env_file: 
  #     - ./env/mongo.env
  # backend:
  #   build: ./backend
  #   # build:
  #   #   context: ./backend
  #   #   dockerfile: Dockerfile
  #   #   args:
  #   #     some-arg: 1
  #   ports:
  #     - '80:80'
  #   volumes: 
  #     - ./backend:/app
  #   env_file: 
  #     - ./env/backend.env
  #   depends_on:
  #     - mongodb
  frontend:
    container_name: hwf
    image: happy-wallet-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      # - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true
      # - FAST_REFRESH = false
    stdin_open: true
    tty: true
    command: npm run dev

# volumes:
#   node_modules:
  