// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type EGroup struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Expense struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Amount    float64   `json:"amount"`
	UserID    int64     `json:"user_id"`
	GroupCode string    `json:"group_code"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Share struct {
	ID         int64           `json:"id"`
	ExpenseID  int64           `json:"expense_id"`
	UserID     int64           `json:"user_id"`
	ShareType  string          `json:"share_type"`
	ShareValue sql.NullFloat64 `json:"share_value"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
