// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Expense struct {
	ID            int64         `json:"id"`
	TeamID        sql.NullInt64 `json:"team_id"`
	Goal          string        `json:"goal"`
	Amount        string        `json:"amount"`
	Currency      string        `json:"currency"`
	SharingMethod string        `json:"sharing_method"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type ExpenseDetail struct {
	ID           int64          `json:"id"`
	ExpenseID    sql.NullInt64  `json:"expense_id"`
	MemberID     sql.NullInt64  `json:"member_id"`
	ActualAmount sql.NullString `json:"actual_amount"`
	SharedAmount sql.NullString `json:"shared_amount"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Team struct {
	ID          int64                 `json:"id"`
	TeamName    string                `json:"team_name"`
	Currency    string                `json:"currency"`
	TeamMembers pqtype.NullRawMessage `json:"team_members"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type TeamMember struct {
	ID              int64         `json:"id"`
	TeamID          sql.NullInt64 `json:"team_id"`
	MemberName      string        `json:"member_name"`
	LinkedAccountID sql.NullInt64 `json:"linked_account_id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}
