// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateExpenses(ctx context.Context, arg CreateExpensesParams) (Expense, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	DeleteEGroup(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetEGroup(ctx context.Context, id int64) (EGroup, error)
	GetExpense(ctx context.Context, id int64) (GetExpenseRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListEGroup(ctx context.Context, arg ListEGroupParams) ([]EGroup, error)
	ListExpenses(ctx context.Context) ([]ListExpensesRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	QueryEGroup(ctx context.Context, arg QueryEGroupParams) (EGroup, error)
	QueryUser(ctx context.Context, arg QueryUserParams) (User, error)
	UpdateEGroup(ctx context.Context, arg UpdateEGroupParams) (EGroup, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
